[package]
name = "markov_namegen"
version = "0.2.1"
edition = "2021"
authors = ["joeclark-phd <joe@joeclark.net>"]
license = "MIT"
repository = "https://github.com/joeclark-phd/markov_namegen"
description = """
Random text generators based on Markov models.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multimarkov = "0.3.2"
regex = "1.8.1"
is-vowel = "0.1.0"
